name:                solga-test
version:             0.1.0.0
homepage:            https://github.com/githubuser/solga-test#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - solga
  - solga-swagger
  - bytestring
  - http-types
  - wai
  - wai-extra
  - aeson
  - warp
  - text
  - swagger2

executables:
  solga-test:
    source-dirs:      src
    main:             Main.hs
